# Generated by Django 6.0.2 on 2026-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
